### ISSUE TITLE
Decrypt PDF with "default" password

### ISSUE THREAD

**Issue by jotae1e** [FemiOfficial/Encrypt-Decrypt-PDF-Nodejs#1]
As you already know, some pdfs are encrypted to restrict some options, such as viewing, etc. with a "default" pasword (protection flags)

Does this library support the option to decrypt this type of documents?

You can read at the end of this document:
https://pdfhummus.com/post/147451287581/hummus-1058-and-pdf-writer-updates-encryption

In the linux command line, I can get it work with the command decrypt without password:

`qpdf --decrypt input.pdf output.pdf
`

(input.pdf have restriction flags)

Thanks for your work

**Comment by FemiOfficial** [comment]
Hi @jotae1e, Thanks for that feedback. However, PDFs with viewing restrictions (encrypted or locked with password). Will not decrypt successfully with qpdf (you should get an error saying 'invalid password') except the correct password is provided.

The library does the encryption/decryption programmatically.
